module.exports = {
    SIGN_IN_SUCCESS : '로그인 성공',
    INVALID_PW : '잘못된 비밀번호 입니다.',
    INVALID_USER : '존재하지 않는 아이디입니다.',
    SIGN_UP_FAIL : '회원가입 실패',
    SIGN_UP_SUCCESS : '회원가입 성공',
    LIST_SUCCESS : '데이터 불러오기 성공',
    LIST_FAIL : '데이터 불러오기 실패',
    MISS_DATA : '필요한 데이터 누락',
    POST_FAIL : '게시물 작성 오류',
    POST_SUCCESS : '게시물 작성 성공',
    REQUEST_FAIL : '신청 실패',
    REQUEST_SUCCESS : '신청 성공',
    APPROVAL_SUCCESS : '승인 성공',
    APPROVAL_FAIL : '승인 실패',
    UNAUTHORIZED: '유효하지 않은 토큰',
    TOKEN_EXPIRED: '토큰 만료',
    GET_USER_INFO_SUCCESS: '유저 정보 확인 성공',
    DELETE_USER_SUCCESS: '회원 탈퇴 성공',
}